ALTER TABLE usuarios
    MODIFY COLUMN nome VARCHAR(150) NOT NULL,
    MODIFY COLUMN email VARCHAR(255) NOT NULL,
    ADD COLUMN nick VARCHAR(30) NULL,
    ADD COLUMN foto LONGTEXT NULL,
    ADD COLUMN plano VARCHAR(20) NOT NULL DEFAULT 'GRATUITO',
    ADD COLUMN tipo_conta VARCHAR(20) NOT NULL DEFAULT 'USUARIO',
    ADD COLUMN status_conta VARCHAR(20) NOT NULL DEFAULT 'ATIVO';

CREATE UNIQUE INDEX uk_usuarios_nick
    ON usuarios (nick);
